version: '3'
services:
  react-app:
    build:
       context: . # Skąd brać pliki
       dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # Mapuje tak jak port . to aktualny folder /app to folder w kontenerze
  tests:
    build:
       context: .
       dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    